spring:
  profiles:
    active: local # 실행 될 서버
    group:
      local: local_server, common, secret
      blue: blue_server, common, secret
      green: green_server, common, secret
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# 각 서버의 설정
---

spring:
  config:
    activate:
      on-profile: local_server
server:
  port: 8080
client:
  address: http://localhost:3000
---

spring:
  config:
    activate:
      on-profile: blue_server
server:
  port: 8080
client:
  address: https://d9pmshlk8tg8l.cloudfront.net # 프론트엔드 S3로 배포된 도메인주소
---

spring:
  config:
    activate:
      on-profile: green_server
server:
  port: 9090
client:
  address: https://d9pmshlk8tg8l.cloudfront.net
---
# ??? ?? ??
spring:
  config:
    activate:
      on-profile: common
mybatis:
  mapper-locations:
    - mappers/*.xml
